version: "3.7"

services:
  webvote:
    build: .
    container_name: voteweb
    image: vote-web-img
    restart: always
    environment:
      - APP_NAME=VoteApp
    expose:
      - 9000
    command: gunicorn vote_app.wsgi:application --bind 0.0.0.0:9000 --workers 3

  nginx:
    build: ./vote_app/nginx
    image: vote-nginx-img
    container_name: votenginx
    restart: always
    ports:
      - 8000:80
    depends_on:
      - webvote

