version: "3.7"

services:
  # Moderator App
  webmoderator:
    build: ./moderator_app
    env_file:
      - ./moderator_app/.env
    image: moderator-web-img
    container_name: moderatorweb
    restart: always
    expose:
      - "9100"
    command: gunicorn moderator_app.wsgi:application --bind 0.0.0.0:9100 --workers 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webmoderator.rule=Host(\"moderator.idugemea.eu\")"
      - "traefik.http.routers.webmoderator.entrypoints=websecure"
      - "traefik.http.routers.webmoderator.tls.certresolver=letsencrypt"
      - "traefik.http.services.webmoderator.loadbalancer.server.port=9100"
      
  # Voting App
  webvote:
    build: ./vote_app
    env_file:
      - ./vote_app/.env
    image: vote-web-img
    container_name: voteweb
    restart: always
    expose:
      - "9000"
    command: gunicorn vote_app.wsgi:application --bind 0.0.0.0:9000 --workers 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webvote.rule=Host(\"vote.idugemea.eu\")"
      - "traefik.http.routers.webvote.entrypoints=websecure"
      - "traefik.http.routers.webvote.tls.certresolver=letsencrypt"
      - "traefik.http.services.webvote.loadbalancer.server.port=9000"

  # Traefik Reverse Proxy
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
      - "8081:8080"  # Optional dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/letsencrypt/acme.json:/letsencrypt/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(\"traefik.idugemea.eu\")"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
