# Generated by Django 3.2.16 on 2025-03-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=100)),
                ('speaker', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('session_id',), name='unique_session'),
        ),
    ]
